# Generated by Django 4.2.3 on 2023-07-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatingroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='writer',
            new_name='type',
        ),
    ]
