# Generated by Django 4.2.3 on 2023-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_writer_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatingroom',
            name='temp1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chatingroom',
            name='temp2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='temp1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='temp2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
