# Generated by Django 4.2.3 on 2023-07-27 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatingroom_temp1_alter_chatingroom_temp2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatingroom',
            old_name='temp1',
            new_name='name',
        ),
    ]
