# Generated by Django 4.2.3 on 2023-07-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_rename_temp1_chatingroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatingroom',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
