# Generated by Django 4.2.3 on 2023-07-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_remove_message_temp1_remove_message_temp2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
    ]
